ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

exclude: ^include/(fmt|magic_enum|EcoMug|CLI11)/

repos:
- repo: https://github.com/psf/black
  rev: "22.10.0"
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: check-json
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    args: ["-L", "hist"]

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v15.0.4
  hooks:
   - id: clang-format
     types_or: [c++]

- repo: https://github.com/asottile/pyupgrade
  rev: "v3.2.2"
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]
