/MUG/Manager/Logging/LogLevelScreen summary
# /MUG/Manager/Randomization/Seed 2

/MUG/Geometry/IncludeGDMLFile /home/gipert/sw/src/mugraphy/src/geom/geometry.gdml
/MUG/Output/FileName detector-hits.root

/run/initialize

/MUG/Generator/ThetaMax 20 deg
/MUG/Generator/MomentumMin 20 GeV/c

# /MUG/Stacking/KillSecondaries false
# /MUG/Stacking/KillSecondaries true

# /MUG/Geometry/PrintListOfLogicalVolumes
# /MUG/Geometry/PrintListOfPhysicalVolumes

/run/beamOn 1000
